### PR TITLE
abgabe: update build description

### LINKED ISSUE #49: Update build tool instructions
https://github.com/software-challenge/docs/pull/47#pullrequestreview-697002794
> Instructions for Eclipse and NetBeans are likely no longer correct and Ant is still mentioned. That should be corrected in another PR.

@SKoschnicke how should we proceed regarding the IDE instructions though? Shall we add IDEA? Remove Netbeans?

As for ant, we still ship with it and I just fixed a little oversight in the buildscript: https://github.com/software-challenge/backend/commit/440dbae139926bc33a1d0cebce6d24a9b5edc892

### PR DESCRIPTION
**Pull request by FalconsSky**
resolves #49

### CODE REVIEW

**Review by jnccd — COMMENTED** [review]
Why are we removing the NetBeans section?
Is the IDE discontinued?
I would keep it in the event someone still uses NetBeans

**Comment by xeruf** [comment]
But we would have to update the instructions, they are probably outdated, so unless you know someone or a team asks for it I agree with the removal.

**Comment by FalconsSky** [comment]
tbh I did not look at NetBeans due to my assumption that nobody usses this IDE anymore.
The instruction of Eclipse at least are up to date.

**Review by jnccd — APPROVED** [review]
Since the eclipse pictures are so old I assume nothing changed for the eclipse section, so I also expect NetBeans to not change substantially either, but I dont think this section is important enough to warrant a long discussion over it

**Pull request merged**
